
package ru.tsystems.shalamov.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DriverActivityWebService", targetNamespace = "http://ws.shalamov.tsystems.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DriverActivityWebService {


    /**
     * 
     * @param personalNumber
     */
    @WebMethod
    @RequestWrapper(localName = "shiftBegin", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.ShiftBegin")
    @ResponseWrapper(localName = "shiftBeginResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.ShiftBeginResponse")
    public void shiftBegin(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

    /**
     * 
     * @param personalNumber
     * @return
     *     returns ru.tsystems.shalamov.ws.DriverAssignmentModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverAssignmentInformation", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.GetDriverAssignmentInformation")
    @ResponseWrapper(localName = "getDriverAssignmentInformationResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.GetDriverAssignmentInformationResponse")
    public DriverAssignmentModel getDriverAssignmentInformation(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

    /**
     * 
     * @param personalNumber
     */
    @WebMethod
    @RequestWrapper(localName = "shiftEnd", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.ShiftEnd")
    @ResponseWrapper(localName = "shiftEndResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.ShiftEndResponse")
    public void shiftEnd(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

    /**
     * 
     * @param personalNumber
     */
    @WebMethod
    @RequestWrapper(localName = "driverStatusToAuxiliary", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToAuxiliary")
    @ResponseWrapper(localName = "driverStatusToAuxiliaryResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToAuxiliaryResponse")
    public void driverStatusToAuxiliary(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

    /**
     * 
     * @param personalNumber
     */
    @WebMethod
    @RequestWrapper(localName = "driverStatusToRest", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToRest")
    @ResponseWrapper(localName = "driverStatusToRestResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToRestResponse")
    public void driverStatusToRest(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

    /**
     * 
     * @param cargoIdentifier
     */
    @WebMethod
    @RequestWrapper(localName = "cargoStatusChangedToDelivered", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.CargoStatusChangedToDelivered")
    @ResponseWrapper(localName = "cargoStatusChangedToDeliveredResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.CargoStatusChangedToDeliveredResponse")
    public void cargoStatusChangedToDelivered(
            @WebParam(name = "CargoIdentifier", targetNamespace = "")
            String cargoIdentifier);

    /**
     * 
     * @param cargoIdentifier
     */
    @WebMethod
    @RequestWrapper(localName = "cargoStatusChangedToShipped", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.CargoStatusChangedToShipped")
    @ResponseWrapper(localName = "cargoStatusChangedToShippedResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.CargoStatusChangedToShippedResponse")
    public void cargoStatusChangedToShipped(
            @WebParam(name = "CargoIdentifier", targetNamespace = "")
            String cargoIdentifier);

    /**
     * 
     * @param personalNumber
     */
    @WebMethod
    @RequestWrapper(localName = "driverStatusToPrimary", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToPrimary")
    @ResponseWrapper(localName = "driverStatusToPrimaryResponse", targetNamespace = "http://ws.shalamov.tsystems.ru/", className = "ru.tsystems.shalamov.ws.DriverStatusToPrimaryResponse")
    public void driverStatusToPrimary(
            @WebParam(name = "PersonalNumber", targetNamespace = "")
            String personalNumber);

}
