
package ru.tsystems.shalamov.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
// @org.springframework.stereotype.Service  - does not help
@WebServiceClient(name = "DriverActivityWebServiceImplService", targetNamespace = "http://ws.shalamov.tsystems.ru/", wsdlLocation = "http://localhost:8080/ws/services/activity?wsdl")
public class DriverActivityWebServiceImplService
    extends Service
{

    private final static URL DRIVERACTIVITYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRIVERACTIVITYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DRIVERACTIVITYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.shalamov.tsystems.ru/", "DriverActivityWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/services/activity?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRIVERACTIVITYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DRIVERACTIVITYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DriverActivityWebServiceImplService() {
        super(__getWsdlLocation(), DRIVERACTIVITYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DriverActivityWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRIVERACTIVITYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DriverActivityWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DRIVERACTIVITYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public DriverActivityWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRIVERACTIVITYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public DriverActivityWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DriverActivityWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DriverActivityWebService
     */
    @WebEndpoint(name = "DriverActivityWebServiceImplPort")
    public DriverActivityWebService getDriverActivityWebServiceImplPort() {
        return super.getPort(new QName("http://ws.shalamov.tsystems.ru/", "DriverActivityWebServiceImplPort"), DriverActivityWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DriverActivityWebService
     */
    @WebEndpoint(name = "DriverActivityWebServiceImplPort")
    public DriverActivityWebService getDriverActivityWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.shalamov.tsystems.ru/", "DriverActivityWebServiceImplPort"), DriverActivityWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRIVERACTIVITYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DRIVERACTIVITYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DRIVERACTIVITYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
